version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: credit_db
      POSTGRES_USER: credit_user
      POSTGRES_PASSWORD: credit_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U credit_user -d credit_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://credit_user:credit_pass@db:5432/credit_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./credit_system:/app/credit_system

  celery:
    build: .
    command: celery -A credit_system worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://credit_user:credit_pass@db:5432/credit_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./credit_system:/app/credit_system

volumes:
  postgres_data:
