# Generated by Django 4.2.7 on 2025-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='legacy_loan_id',
            field=models.CharField(blank=True, help_text='Legacy loan ID from imported data', max_length=50, null=True, unique=True),
        ),
    ]
